name: Run Tests and Check Coverage

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Run Tests and Check Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Install dependencies
        run: bundle install

      - name: Set up database
        run: |
          bin/rails db:create db:schema:load

      - name: Run tests with SimpleCov
        run: |
          bin/rails db:migrate RAILS_ENV=test
          RESULT=$(bundle exec rspec)

      - name: Check coverage
        run: |
          # Extract coverage percentage from the rspec output
          COVERAGE=$(echo "$RESULT" | sed -n 's/.*Line Coverage: \([0-9.]*\)%.*$/\1/p')
          if (( $(echo "$COVERAGE < 95" | bc -l) )); then
            echo "Code coverage ($COVERAGE%) is below the threshold of 95%."
            echo "::set-output name=job-status::failure"
          else
            echo "Code coverage ($COVERAGE%) meets the threshold of 95%."
            echo "::set-output name=job-status::success"
          fi
        id: check-coverage

      - name: Fail job if coverage is below threshold
        if: steps.check-coverage.outputs.job-status == 'failure'
        run: exit 1
