name: 🚨 Check for Dependency Vulnerabilities

on:
  push:
    branches:
      - "**"

jobs:
  bundler-audit:
    name: Run Bundler Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Bundler Audit
        run: |
          bundle exec bundler-audit check --update
